# Generated by Django 4.2.28 on 2026-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentconfig',
            name='facebook_page_api',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='aiagentconfig',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
