# Generated by Django 6.0.2 on 2026-02-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aiagentconfig_facebook_page_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='package_name',
            field=models.CharField(blank=True, default='Free Trial', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
