# Generated by Django 6.0.2 on 2026-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('NONE', 'Not Submitted'), ('PENDING', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NONE', max_length=20),
        ),
    ]
