# Generated by Django 4.2.28 on 2026-02-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_home_address_userprofile_kyc_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentconfig',
            name='blocked_post_ids',
            field=models.TextField(blank=True, help_text='Newline-separated list of Facebook post IDs to block'),
        ),
        migrations.AddField(
            model_name='aiagentconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn AI agent on/off'),
        ),
    ]
