# Generated by Django 6.0.2 on 2026-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_aiagentconfig_blocked_post_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentconfig',
            name='google_sheet_id',
            field=models.CharField(blank=True, help_text='Google Sheet ID for reports', max_length=200),
        ),
    ]
