# Generated by Django 6.0.2 on 2026-02-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_aiagentconfig_google_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_info',
            field=models.TextField(blank=True, help_text='Details about your business/Facebook page'),
        ),
    ]
