# Generated by Django 6.0.2 on 2026-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscription_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='kyc_document',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/back/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_documents/front/'),
        ),
    ]
