# Generated by Django 6.0.2 on 2026-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_kyc_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for KYC rejection (shown to user)'),
        ),
    ]
